---
k3s_server_extra_args: ""
cilium_version: "1.16.6"
hetzner_ccm_version: "1.22.0"

ks_server_init_args: |-
  {% if groups['servers'] | length > 1 %}
    {% if inventory_hostname == groups['servers'][0] %}
      --cluster-init \
    {% else %}
      --server https://{{ k3s_api_endpoint }}:6443 \
    {% endif %}
  {% endif %}

k3s_server_common_args: |-
  --token {{ k3s_token }} \
  --advertise-address {{ k3s_node_private_ip }} \
  --node-ip {{ k3s_node_private_ip }} \
  --node-external-ip {{ ansible_default_ipv4.address }} \
  --tls-san {{ k3s_api_endpoint }} \
  --tls-san {{ k3s_node_private_ip }} \
  --tls-san {{ ansible_default_ipv4.address }} \
  --data-dir {{ k3s_data_dir }} \
  --cluster-cidr {{ cluster_cidr_network }} \
  --service-cidr {{ service_cidr_network }} \
  --flannel-backend=none \
  --disable-network-policy \
  --disable-kube-proxy \
  --disable-cloud-controller \
  --egress-selector-mode disabled \
  --disable local-storage \
  --disable metrics-server \
  --disable servicelb \
  --disable traefik

k3s_server_args: |-
  {{ ks_server_init_args }} \
  {{ k3s_server_common_args }} 
