---
argument_specs:
  main:
    short_description: setup k3s servers
    options:
      k3s_apiserver_endpoint:
        description: virtual ip-address configured on each master
        required: true
