---
- name: check if hcloud secret is present
  ansible.builtin.command: k3s kubectl -n kube-system get secret hcloud
  register: hcloud_secret_present
  ignore_errors: true

- name: create hcloud secret
  ansible.builtin.command: k3s kubectl -n kube-system create secret generic hcloud --from-literal=token={{ lookup('ansible.builtin.env', 'HCLOUD_TOKEN') }} --from-literal=network={{ network_id }}
  environment:
    KUBECONFIG: "/etc/rancher/k3s/k3s.yaml"
  when: hcloud_secret_present.rc != 0
